name = "news-reader"
compatibility_date = "2023-01-01"

# Correctly specify the build output directory for Pages
[build]
command = "npm run build"

[site]
bucket = "out"

# This is what Pages is looking for
[build.upload]
format = "directory"
pages_build_output_dir = "out"